---
- name: Reboot host
  hosts: '{{ target }}'
  tasks:
    - name: Reboot
      shell: reboot
      async: 0
      poll: 0
    - name: Wait for reboot
      local_action: wait_for host={{ target }} state=start port=22 delay=30 timeout=300 connect_timeout=15
